    name: Shell Script Lint and Test

    on:
      push:
        paths:
          - '**/*.sh'  # 仅在提交包含 .sh 文件时触发
      pull_request:
        paths:
          - '**/*.sh'

    jobs:
      lint_and_test:
        runs-on: ubuntu-latest

        steps:
        # 1. 检出代码
        - name: Checkout repository
          uses: actions/checkout@v3

        # 2. 安装工具
        - name: Install Shellcheck and Shfmt
          run: |
            sudo apt-get update
            sudo apt-get install -y shellcheck
            curl -sS https://webinstall.dev/shfmt | bash

        # 3. 检测 Shell 脚本的语法
        - name: Lint with Shellcheck
          run: |
            find . -name "*.sh" -exec shellcheck {} +

        # 4. 检测 Shell 脚本的格式
        - name: Format with Shfmt
          run: |
            shfmt -d .

        # 5. 运行 Bats 测试
        - name: Install Bats
          run: |
            git clone https://github.com/bats-core/bats-core.git /tmp/bats-core
            /tmp/bats-core/install.sh /usr/local
        - name: Run Bats Tests
          run: |
            find . -name "*.bats" -exec bats {} +

